#!/usr/bin/env bash
set -euo pipefail

# Bastion Shield — EC2 Deployment Script
# Usage: bash scripts/deploy-ec2.sh [--build-only|--domain example.com]
# Run on fresh Ubuntu 24.04 t3.micro (or larger)

REPO_URL="${BASTION_REPO_URL:-https://github.com/dgboy-ai/Bastion.git}"
BRANCH="${BASTION_BRANCH:-main}"
DASHBOARD_DIR="$HOME/bastion/dashboard"
PYTHON_SRC="$HOME/bastion"

echo "=== Bastion Shield EC2 Deployment ==="
echo "Target: Ubuntu 24.04, Node.js 20, Python 3.11"

# ─── Parse args ──────────────────────────────────
BUILD_ONLY=false
DOMAIN=""
for arg in "$@"; do
    case "$arg" in
        --build-only) BUILD_ONLY=true ;;
        --domain=*) DOMAIN="${arg#*=}" ;;
        --domain) echo "Use --domain=example.com"; exit 1 ;;
    esac
done

# ─── Swap file for t3.micro (1GB RAM) ────────────
if [ "$(free -m | awk '/^Mem:/{print $2}')" -lt 2048 ] && [ ! -f /swapfile ]; then
    echo ">>> Creating 2GB swap file..."
    sudo fallocate -l 2G /swapfile
    sudo chmod 600 /swapfile
    sudo mkswap /swapfile
    sudo swapon /swapfile
    echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
    echo "Swap: OK"
fi

# ─── System packages ─────────────────────────────
echo ">>> Installing system dependencies..."
sudo apt-get update -qq
sudo apt-get install -y -qq \
    curl ca-certificates gnupg \
    python3.11 python3.11-venv python3-pip \
    git nginx ufw

# ─── Node.js 20 ──────────────────────────────────
if ! command -v node &>/dev/null; then
    echo ">>> Installing Node.js 20..."
    curl -fsSL https://deb.nodesource.com/setup_20.x | sudo bash -
    sudo apt-get install -y -qq nodejs
fi
echo "Node: $(node --version)"
echo "npm: $(npm --version)"

# ─── Clone repo ──────────────────────────────────
if [ ! -d "$HOME/bastion" ]; then
    echo ">>> Cloning Bastion..."
    git clone --branch "$BRANCH" "$REPO_URL" "$HOME/bastion"
else
    echo ">>> Repo exists, pulling latest..."
    cd "$HOME/bastion"
    git pull origin "$BRANCH"
fi

# ─── Dashboard (Next.js) build ──────────────────
echo ">>> Building dashboard..."
cd "$DASHBOARD_DIR"
npm ci
npm run build
echo "Dashboard build: OK"

# ─── Python package ──────────────────────────────
echo ">>> Installing Python package..."
cd "$PYTHON_SRC"
python3.11 -m venv .venv
# shellcheck disable=SC1091
source .venv/bin/activate
pip install --quiet -e ".[mcp,a2a,groq]"
echo "Python install: OK"

# ─── Schema migrations ──────────────────────────
echo ">>> Running schema migrations..."
if [ -n "${BASTION_CONN:-}" ]; then
    cd "$PYTHON_SRC"
    BASTION_CONN="$BASTION_CONN" python run_remaining_migrations.py
    echo "Migrations: OK"
else
    echo "Migrations: SKIPPED (BASTION_CONN not set — will run on first start)"
fi

if [ "$BUILD_ONLY" = true ]; then
    echo "=== Build complete. Skipping service setup (--build-only) ==="
    exit 0
fi

# ─── Environment file ────────────────────────────
PUBLIC_IP=$(curl -s http://checkip.amazonaws.com 2>/dev/null || echo "localhost")
ENV_FILE="$DASHBOARD_DIR/.env.production"
if [ ! -f "$ENV_FILE" ]; then
    echo ">>> Creating .env.production..."
    echo "# Bastion Production Config — generated by deploy-ec2.sh" > "$ENV_FILE"
    echo "# Edit this file with your real credentials." >> "$ENV_FILE"
    echo "" >> "$ENV_FILE"

    if [ -n "${BASTION_CONN:-}" ]; then
        echo "BASTION_CONN=$BASTION_CONN" >> "$ENV_FILE"
    else
        echo "# BASTION_CONN=postgresql://user:password@host:port/database?sslmode=require" >> "$ENV_FILE"
    fi

    if [ -n "${BASTION_API_KEY:-}" ]; then
        echo "BASTION_API_KEY=$BASTION_API_KEY" >> "$ENV_FILE"
    else
        echo "# BASTION_API_KEY=your-api-key" >> "$ENV_FILE"
    fi

    if [ -n "${GROQ_API_KEY:-}" ]; then
        echo "GROQ_API_KEY=$GROQ_API_KEY" >> "$ENV_FILE"
    fi

    if [ -n "${AWS_ACCESS_KEY_ID:-}" ] && [ -n "${AWS_SECRET_ACCESS_KEY:-}" ]; then
        echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> "$ENV_FILE"
        echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> "$ENV_FILE"
    fi

    echo "CORS_ALLOW_ORIGINS=http://localhost:3000,http://$PUBLIC_IP" >> "$ENV_FILE"
    echo "BASTION_LOG_LEVEL=INFO" >> "$ENV_FILE"

    echo ""
    echo "================================================================"
    echo "  EDIT THIS FILE with real credentials:"
    echo "    nano $ENV_FILE"
    echo "  Required: BASTION_CONN, BASTION_API_KEY"
    echo "  Optional: GROQ_API_KEY, AWS_*"
    echo "================================================================"
    echo ""
else
    echo ">>> .env.production found, sourcing existing config"
fi

# ─── Firewall (UFW) ─────────────────────────────
echo ">>> Configuring firewall..."
sudo ufw --force reset
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp    # SSH
sudo ufw allow 80/tcp    # HTTP
if [ -n "$DOMAIN" ]; then
    sudo ufw allow 443/tcp    # HTTPS
fi
sudo ufw --force enable
echo "Firewall: OK"

# ─── PM2 process manager ─────────────────────────
echo ">>> Installing PM2..."
sudo npm install -g pm2

# ─── Log directory ──────────────────────────────
mkdir -p "$HOME/bastion/logs"

# ─── Start services ──────────────────────────────
echo ">>> Starting services..."
source "$PYTHON_SRC/.venv/bin/activate"

# Dashboard (Next.js on :3000)
pm2 delete bastion-dashboard 2>/dev/null || true
pm2 start npm --name "bastion-dashboard" \
    --cwd "$DASHBOARD_DIR" \
    -- start \
    -- --port 3000 2>&1 | tail -5

# MCP Server (Python on :9997)
pm2 delete bastion-mcp 2>/dev/null || true
pm2 start "$PYTHON_SRC/.venv/bin/python" --name "bastion-mcp" \
    -- -m bastion.mcp_server \
    --transport http --host 0.0.0.0 --port 9997 \
    --log-file "$HOME/bastion/logs/mcp.log" 2>&1 | tail -5

# A2A Server (Python on :9998)
pm2 delete bastion-a2a 2>/dev/null || true
pm2 start "$PYTHON_SRC/.venv/bin/python" --name "bastion-a2a" \
    -- -m bastion.a2a_server \
    --log-file "$HOME/bastion/logs/a2a.log" 2>&1 | tail -5

# Save PM2 config for auto-restart
pm2 save
pm2 startup systemd -u "$USER" --hp "$HOME" 2>/dev/null || true

echo ">>> PM2 status:"
pm2 status

# ─── Health checks ──────────────────────────────
echo ">>> Running health checks..."
sleep 3
HEALTHY=true
if curl -sf http://127.0.0.1:3000/api/health > /dev/null 2>&1; then
    echo "  Dashboard :3000 — OK"
else
    echo "  Dashboard :3000 — FAIL (may need more time)"
    HEALTHY=false
fi
if curl -sf http://127.0.0.1:9997/health > /dev/null 2>&1; then
    echo "  MCP :9997 — OK"
else
    echo "  MCP :9997 — FAIL (may need more time)"
    HEALTHY=false
fi
if curl -sf http://127.0.0.1:9998/health > /dev/null 2>&1; then
    echo "  A2A :9998 — OK"
else
    echo "  A2A :9998 — FAIL (may need more time)"
    HEALTHY=false
fi

# ─── Nginx reverse proxy ─────────────────────────
echo ">>> Configuring Nginx..."

sudo tee /etc/nginx/sites-available/bastion > /dev/null << NGINXEOF
server {
    listen 80;
    server_name ${DOMAIN:-$PUBLIC_IP};

    client_max_body_size 10m;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;

    # Dashboard
    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_cache_bypass \$http_upgrade;
    }

    # MCP Server
    location /mcp/ {
        proxy_pass http://127.0.0.1:9997/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_read_timeout 120s;
    }

    # A2A Server
    location /a2a/ {
        proxy_pass http://127.0.0.1:9998/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_read_timeout 120s;
    }
}
NGINXEOF

sudo ln -sf /etc/nginx/sites-available/bastion /etc/nginx/sites-enabled/
sudo rm -f /etc/nginx/sites-enabled/default
sudo nginx -t && sudo systemctl reload nginx

# ─── HTTPS via Let's Encrypt (optional) ──────────
if [ -n "$DOMAIN" ]; then
    echo ">>> Setting up HTTPS for $DOMAIN..."
    sudo apt-get install -y -qq certbot python3-certbot-nginx
    sudo certbot --nginx --non-interactive --agree-tos \
        -d "$DOMAIN" \
        --email "${BASTION_ADMIN_EMAIL:-admin@$DOMAIN}" \
        --redirect
    echo "HTTPS: OK — https://$DOMAIN"
else
    echo "HTTPS: SKIPPED (no --domain flag). Deploying on HTTP only."
    echo "  Set up HTTPS later with:"
    echo "    sudo certbot --nginx -d YOUR_DOMAIN"
fi

# ─── PM2 log rotation ───────────────────────────
pm2 install pm2-logrotate 2>/dev/null || true
pm2 set pm2-logrotate:max_size 50M 2>/dev/null || true
pm2 set pm2-logrotate:retain 7 2>/dev/null || true

echo ""
echo "=== Deployment Complete ==="

if [ -n "$DOMAIN" ]; then
    echo "Dashboard:  https://$DOMAIN"
    echo "MCP Server: https://$DOMAIN/mcp/"
    echo "A2A Server: https://$DOMAIN/a2a/"
else
    echo "Dashboard:  http://$PUBLIC_IP"
    echo "MCP Server: http://$PUBLIC_IP/mcp/"
    echo "A2A Server: http://$PUBLIC_IP/a2a/"
fi

echo ""
echo "Management:"
echo "  pm2 status          — service status"
echo "  pm2 logs            — tail all logs"
echo "  pm2 restart all     — restart services"
echo "  pm2 stop all        — stop services"

if [ "$HEALTHY" = false ]; then
    echo ""
    echo "⚠️  Some health checks failed. Services may need a moment to start."
    echo "   Run 'pm2 status' and 'pm2 logs' to investigate."
fi

echo ""
echo "Post-deploy checklist:"
echo "  [ ] Edit $ENV_FILE with real credentials"
echo "  [ ] Restart: pm2 restart all"
echo "  [ ] Set up DNS A record pointing to $PUBLIC_IP"
echo "  [ ] Run: sudo certbot --nginx -d YOUR_DOMAIN (for HTTPS)"
echo "  [ ] Verify: curl http://$PUBLIC_IP/api/health"
